"""add razorpay fields to orders

Revision ID: 3c04b2e7d732
Revises: 1ee68921a18a
Create Date: 2026-06-17 10:49:25.939612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c04b2e7d732'
down_revision: Union[str, Sequence[str], None] = '1ee68921a18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_order_id')
    # ### end Alembic commands ###
