"""add vendor id to products

Revision ID: 63aa9d9beb64
Revises: e90af2743d2a
Create Date: 2026-06-17 16:25:19.154221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63aa9d9beb64'
down_revision: Union[str, Sequence[str], None] = 'e90af2743d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'vendor_id')
    # ### end Alembic commands ###
