"""add razorpay columns to orders

Revision ID: e90af2743d2a
Revises: 3c04b2e7d732
Create Date: 2026-06-17 11:00:07.244918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90af2743d2a'
down_revision: Union[str, Sequence[str], None] = '3c04b2e7d732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_signature')
    op.drop_column('orders', 'razorpay_payment_id')
    # ### end Alembic commands ###
